name             'deploy-test'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures deploy-test'
long_description 'Installs/Configures deploy-test'
version          '0.1.0'

depends 'apt',                  '= 2.6.0'
depends 'application',          '= 4.1.4'